# Generated by Django 5.2.11 on 2026-03-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imei", models.CharField(max_length=15, unique=True)),
                ("brand", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                        ],
                        default="Good",
                        max_length=20,
                    ),
                ),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "negotiated_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Processed", "Processed"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
