# Generated by Django 5.2.11 on 2026-03-05 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyback",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buybacks",
                to="api.customer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("new_phone", "New Phone"),
                    ("used_phone", "Used Phone"),
                    ("accessories", "Accessories"),
                    ("services", "Services"),
                ],
                default="new_phone",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repair_tickets",
                to="api.customer",
            ),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repair_tickets",
                to="api.employee",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="api.employee",
            ),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "store_type",
                    models.CharField(
                        choices=[("main", "Main Branch"), ("addon", "Addon Branch")],
                        default="addon",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="api.store",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buyback",
            name="store_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buybacks",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="store_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="store_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="primary_store_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_products",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="store_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repair_tickets",
                to="api.store",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="store_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="api.store",
            ),
        ),
        migrations.CreateModel(
            name="StoreInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_inventory",
                        to="api.product",
                    ),
                ),
                (
                    "store_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="api.store",
                    ),
                ),
            ],
            options={
                "unique_together": {("store_ref", "product")},
            },
        ),
    ]
