# Generated by Django 5.2.11 on 2026-03-05 04:58

from django.db import migrations


def seed_default_stores(apps, schema_editor):
    Store = apps.get_model("api", "Store")
    Employee = apps.get_model("api", "Employee")
    Customer = apps.get_model("api", "Customer")

    main_store, _ = Store.objects.get_or_create(
        code="MAIN",
        defaults={"name": "Main Branch", "store_type": "main"},
    )
    store_a, _ = Store.objects.get_or_create(
        code="STORE_A",
        defaults={"name": "Store A", "store_type": "addon", "parent": main_store},
    )
    store_b, _ = Store.objects.get_or_create(
        code="STORE_B",
        defaults={"name": "Store B", "store_type": "addon", "parent": main_store},
    )

    name_to_store = {
        "Main Branch": main_store,
        "Store A": store_a,
        "Store B": store_b,
    }

    for employee in Employee.objects.all():
        store = name_to_store.get((employee.store or "").strip())
        if store and employee.store_ref_id is None:
            employee.store_ref_id = store.id
            employee.save(update_fields=["store_ref"])

    for customer in Customer.objects.filter(store_ref__isnull=True):
        customer.store_ref_id = main_store.id
        customer.save(update_fields=["store_ref"])


def unseed_default_stores(apps, schema_editor):
    Store = apps.get_model("api", "Store")
    Store.objects.filter(code__in=["MAIN", "STORE_A", "STORE_B"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_buyback_customer_product_category_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_stores, unseed_default_stores),
    ]
