# Generated by Django 5.2.11 on 2026-03-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_seeded_admin_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyback",
            name="cash_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="buyback",
            name="exchange_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="buyback",
            name="exchange_model",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="buyback",
            name="ic_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="buyback",
            name="job_no",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="buyback",
            name="online_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="got_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="in_cash",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="in_online",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="out_cash",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="out_online",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="parts_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="repairticket",
            name="problem",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="cash_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="exchange_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="exchange_model",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="sale",
            name="gift",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="sale",
            name="got_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="ic_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sale",
            name="job_no",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="sale",
            name="online_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="salesperson_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=180)),
                (
                    "out_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "out_online",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("expense_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="api.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("in", "Pending In"), ("out", "Payments Out")],
                        max_length=10,
                    ),
                ),
                ("dealer_name", models.CharField(max_length=180)),
                (
                    "cash_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "online_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("entry_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_entries",
                        to="api.store",
                    ),
                ),
            ],
        ),
    ]
